name: 02-01-Simple Workflow
on: push
#on: workflow_dispatch
jobs: 
  my-first-job:
    runs-on: DESKTOP-5636MPU
    steps:
      - run: echo "Hello World"
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bye World"
